spring:
  application:
    name: DataProcess
server:
  port: 8082

app:
  config:
    security:
      opaque-token:
        enable: true
        introspection-uri: http://127.0.0.1:8081/opaque/token/check
      local-jwt-public-key: false
      net-jwt-public-key-domain: http://127.0.0.1:8081/
      authorization-type: memory
      permit-urls:
        DataProcess:
          - /user/query/all/without/login